
(define (sum term a next b)
  (define (iter a result)
    (if (> a b)
        result
        (iter (next a) (+ (term a) result))))
   (iter a 0))
(define (integral-s f a b n)
	(define h ( / ( - b a) n))
	(define (y k) ( f (+ a (* k h))))
	(define (even k)(= 0 (remainder k 2)))
	(define(index k)
	       (cond ((= 0 k) 1)
	             ((= n k) 1)
	             ((even k) 2)
	             (else 4))
		)
	(define (ty k) (* (index k) (y k)))
	(define (next k) (+ k 1 ))
	(* (/ h 3) (sum ty 0 next n))
  )
(define (cube x) (* x x x))
(display (integral-s cube 0 1 1000))