(define (make-point a b)
  (cons a b))
(define (x-point a)
  (car a))
(define (y-point a)
  (cdr a))


(define (make-segment a b c d)
  (cons (cons a b) (cons c d)))
(define (start-segment a) (car a))
(define (end-segment a) (cdr a))

(define (average a b)
  (/ (+ a b) 2.0))
(define (midpoint-segment a)
  (let ((s (start-segment a))
        (e (end-segment a)))
  (make-point (average (x-point s) (x-point e))
              (average (y-point s) (y-point e)))))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define seg1 (make-segment 1 2 3 5))
(print-point (midpoint-segment seg1))