(define (make-monitored f)
  (define count 0)
  (define (reset-count)
      (set! count 0))
  (define (dispatch m)
    (cond ((eq? m 'reset-count) (reset-count))
          ((eq? m 'how-many-calls?) count)
          ((number? m) (begin 
                         (set! count (+ 1 count))
                         (f m)))
          (else (error "ERROR--MAKE-MONITORED"))))
  dispatch)

(sqrt 2)
(define s (make-monitored sqrt))
(s 100)
(s 10)
(s 1000)
(newline)
(s 'how-many-calls?)