(define (make-account balance p)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m d)
    (cond
    ((and (eq? m p) (eq? d 'withdraw)) withdraw)
    ((and (eq? m p) (eq? d 'deposit)) deposit)
    ((not (eq? m p)) (lambda (x) "Incorrect password"))
    (else (error "Unknown request -- MAKE-ACCOUNT" m ))))
  dispatch)
(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'dsaasdasd 'withdraw) 40)